language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
  include:
    - rust: stable
      env: RUSTFLAGS="-C target-cpu=native"
    - rust: beta
      env: RUSTFLAGS="-C target-cpu=native"
    - rust: nightly
      env: RUSTFLAGS="-C target-cpu=native"
    - rust: nightly
      env: CLIPPY="true"
  allow_failures:
    - rust: nightly
cache: cargo
install:
  - cargo build
script:
  - bash -c "[ $TRAVIS_RUST_VERSION == \"nightly\" ] && cargo test --verbose --all || true"
  - bash -c "[ $TRAVIS_RUST_VERSION == \"nightly\" ] && cargo bench --verbose --all || true"
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
  email: false
